### ISSUE TITLE
[bug] Not possible to find intersection inside of the rectangle

### ISSUE THREAD

**Issue by minusplusminus** [node-vision/strapi-plugin-entity-relationship-chart#27]
Strapi version: 4.11.3
strapi-plugin-entity-relationship-chart version: ^4.1.0
browser version: Chrome  115.0.5790.114 (arm64)

```
[request].1eaa9324.chunk.js:186 Uncaught Error: Not possible to find intersection inside of the rectangle
    at Object.u [as intersectRect] ([request].1eaa9324.chunk.js:186:28481)
    at [request].1eaa9324.chunk.js:186:8859
    at P (main.8ff64f27.js:4093:40506)
    at Object.a ([request].1eaa9324.chunk.js:208:49192)
    at k ([request].1eaa9324.chunk.js:186:8685)
    at [request].1eaa9324.chunk.js:186:6170
    at h ([request].1eaa9324.chunk.js:186:29743)
    at h ([request].1eaa9324.chunk.js:186:6130)
    at [request].1eaa9324.chunk.js:186:4978
    at h ([request].1eaa9324.chunk.js:186:29743)

```
and 

```
inverseJoinColumn missing22  '{"name":"files_related_morphs","joinColumn":{"name":"file_id","referencedColumn":"id"},"morphColumn":{"typeColumn":{"name":"related_type"},"idColumn":{"name":"related_id","referencedColumn":"id"}},"orderBy":{"order":"asc"},"pivotColumns":["file_id","related_type","related_id"]}'
```
The bug results in nodes not properly positioned in window. Expected result is nodes positioned according to screenshot in readme.md. 
When window is opened. Database view is empty too, but API view shows nodes.

**Comment by NMontilva** [comment]
I'm also having this issue

**Comment by SalahAdDin** [comment]
This package is not maintained anymore.
