### ISSUE TITLE
Strapi 5 Support?

### ISSUE THREAD

**Issue by matbrgz** [node-vision/strapi-plugin-entity-relationship-chart#31]
Hello,

I'm trying to use your plugin `strapi-plugin-entity-relationship-chart` with Strapi 5, but I'm encountering an error when building the admin panel. Here are the steps I followed and the error message I received:

```
$ yarn build
✔ Compiling TS (2064ms)
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (140ms)
⠋ Building admin panel
✖ Building admin panel
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                      │
│   [commonjs--resolver] Expression expected in /home/cooper/dev/crm-backend/node_modules/strapi-plugin-entity-relat   │
│   ionship-chart/admin/src/components/PluginIcon/index.js                                                             │
│   file: /home/cooper/dev/crm-backend/node_modules/strapi-plugin-entity-relationship-chart/admin/src/components/Plu   │
│   ginIcon/index.js:10:25                                                                                             │
│                                                                                                                      │
│   8: import OneToMany from '@strapi/icons/OneToMany';                                                                │
│   9:                                                                                                                 │
│   10: const PluginIcon = () => <OneToMany />;                                                                        │
│   ^                                                                                                                  │
│   11:                                                                                                                │
│   12: export default PluginIcon;                                                                                     │
│                                                                                                                      │
│   at getRollupError (file:///home/cooper/dev/crm-backend/node_modules/rollup/dist/es/shared/parseAst.js:395:41)      │
│   at convertProgram (file:///home/cooper/dev/crm-backend/node_modules/rollup/dist/es/shared/parseAst.js:1083:26)     │
│   at parseAst (file:///home/cooper/dev/crm-backend/node_modules/rollup/dist/es/shared/parseAst.js:2068:87)           │
│   at tryParse (file:///home/cooper/dev/crm-backend/node_modules/@strapi/strapi/node_modules/vite/dist/node/chunks/   │
│   dep-p3C6MpSJ.js:7687:12)                                                                                           │
│   at analyzeTopLevelStatements (file:///home/cooper/dev/crm-backend/node_modules/@strapi/strapi/node_modules/vite/   │
│   dist/node/chunks/dep-p3C6MpSJ.js:7707:15)                                                                          │
│   at Object.transformAndCheckExports (file:///home/cooper/dev/crm-backend/node_modules/@strapi/strapi/node_modules   │
│   /vite/dist/node/chunks/dep-p3C6MpSJ.js:9760:68)                                                                    │
│   at Object.transform (file:///home/cooper/dev/crm-backend/node_modules/@strapi/strapi/node_modules/vite/dist/node   │
│   /chunks/dep-p3C6MpSJ.js:9960:41)                                                                                   │
│   at file:///home/cooper/dev/crm-backend/node_modules/rollup/dist/es/shared/node-entry.js:20730:40                   │
│                                                                                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

It appears that there's an issue with compatibility between the plugin and Strapi 5, specifically related to the import of `@strapi/icons/OneToMany`.

Are there any plans to update the plugin to support Strapi 5? If not, could you please provide guidance on how to resolve this error or suggest any possible workarounds?

Thank you for your assistance!

**Comment by Shmuri** [comment]
Did you end up solving the error or, alternatively, finding a different plugin that functions in Strapi v5 and produces something similar?

**Comment by matbrgz** [comment]
> Did you end up solving the error or, alternatively, finding a different plugin that functions in Strapi v5 and produces something similar?

No :(
